# MI²Solutions {.unnumbered #mi2solutions}

Hire a team of experienced researchers. **The blue team** will help you develop good predictive models, create a responsible solution tailored to your needs. **The red team** will help you find and analyse any weaknesses in your predictive models. It will help you confront them with domain knowledge and make sure they are resilient to future changes in the data.


If you need tailor-made solutions for your individual needs, we are happy to help you too. Contact us, we can develop software for you, deploy it, provide training, discuss your needs, verify the quality of your existing solutions.

Below you will find a sample offer for trainings or deployments.

**Research as a service**

Our team has experience not only in groundbreaking research, but also in deploying these research into business.

There are many ways we can help, for example

- help in delivery of champion-challenger evaluations in which we look for potential to increase the effectiveness of predictive models in your company.
- take care of the whole life cycle of the predictive models, from reproducibility of results to constant monitoring and continuous improvement of the model.
- audit models and analyse the sensitivity and vulnerability of the model to incorrect or unexpected behaviours.

We would be happy to discuss how we could help with your organisation!



